# Generated by Django 5.1.7 on 2025-03-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.CharField(max_length=20)),
                ('idDispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dispositivo')),
            ],
        ),
    ]
