# Generated by Django 5.1.7 on 2025-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='consumo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('actuador', 'Actuador'), ('camara', 'Cámara'), ('foco', 'Foco/iluminacion'), ('electrodomestico', 'Electrodoméstio'), ('otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fechaRegistro',
            field=models.DateTimeField(),
        ),
    ]
