# Generated by Django 5.1.7 on 2025-03-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dispositivo_consumo_registro_consumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('electronico', 'Electrónico'), ('camara', 'Cámara'), ('foco', 'Foco/iluminacion'), ('electrodomestico', 'Electrodoméstio'), ('otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='consumo',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
